# Site settings
title: "Tình Yêu Muôn Màu"
url-title: "Tình Yêu Muôn Màu"
description: "Đoàn Bình và Tình Yêu Muôn Màu"
paginate: 100
url: "https://iloves.live"
permalink: /:year/:month/:title/
future: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_words: 25

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
  deploy_style: compressed

gems: [jekyll-paginate]
